# Generated by Django 3.1.5 on 2021-01-10 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0011_auto_20210110_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 20, 33, 19, 267115)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 20, 33, 19, 268030)),
        ),
    ]
