# Generated by Django 3.1.5 on 2021-01-11 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0015_auto_20210110_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 8, 32, 49, 966896)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 8, 32, 49, 966896)),
        ),
    ]
