# Generated by Django 3.1.5 on 2021-01-11 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0021_auto_20210111_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 10, 39, 8, 861896)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 10, 39, 8, 862900)),
        ),
    ]
